; ArgAsm-Super FX (ArgSfx)
; Filename: DEFINES.INC
; Purpose: Equates.
; Source code reconstructed by Sunlitspace542 and contributors.
; Original program copyright (C) 1992-1994 Argonaut Software Ltd.

; Platform Defines

; Target MS-DOS
TARGET_DOS		equ	1

; Target DOS with DOS/16M (ZPM) extender
TARGET_DOS16M	equ	0

; TODO figure out if we can actually target OS/2 with MASM
; Target IBM OS/2
TARGET_OS2		equ	0

; Assembler Version defines

; SASM/SASMX
VERSION_SASM	equ	0
