; ArgAsm-Super FX (ArgSfx)
; Filename: DEFINES.INC
; Purpose: Equates.
; Source code reconstructed by Sunlitspace542 and contributors.
; Original program copyright (C) 1992-1994 Argonaut Software Ltd.

; Target MS-DOS
VERSION_DOS		equ	1

; Target DOS with DOS/16M (ZPM) extender
VERSION_DOS16M	equ	0

; TODO figure out if we can actually target OS/2 with MASM
; Target IBM OS/2
VERSION_OS2		equ	0